### PR TITLE
Replace AWSCore with AWS.jl

### LINKED ISSUE #27: does not play nicely with AWS.jl
This package uses AWSCore.jl which does not interoperate with AWS.jl, the config struct in particular:

```julia
julia> ?CloudWatchLogStream
CloudWatchLogStream(config::AWSConfig, log_group_name, log_stream_name)

Create a reference to a CloudWatch Log Stream on AWS with the log group name and
log stream name. This constructor will automatically fetch the latest [sequence
token](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html#CWL-PutLogEvents-request-sequenceToken) for the stream.

julia> stream = CloudWatchLogStream(AWS.global_aws_config(), "my-group", "my-stream")
MethodError: no method matching CloudWatchLogStream(::AWSConfig, ::String, ::String)
Closest candidates are:
  CloudWatchLogStream(::Any, ::Any, ::Any, ::Any) at /home/ubuntu/.julia/packages/CloudWatchLogs/W1Ltg/src/stream.jl:22
  CloudWatchLogStream(::Dict{Symbol, Any}, ::String, ::String, ::Ref{Union{Nothing, String}}) at /home/ubuntu/.julia/packages/CloudWatchLogs/W1Ltg/src/stream.jl:22
  CloudWatchLogStream(::Dict{Symbol, Any}, ::AbstractString, ::AbstractString) at /home/ubuntu/.julia/packages/CloudWatchLogs/W1Ltg/src/stream.jl:36
```

I think the solution to this is to "just" upgrade to AWS.jl but I'm not sure how heavy a lift that would be.

### PR DESCRIPTION
**Pull request by ararslan**
See #28 for context/discussion. This is the same set of changes but from a branch on the repo rather than from a fork.

Fixes #27.

### CODE REVIEW

**Comment by ararslan** [comment]
Either permissions are still weird or I've messed something up.

**Comment by mattBrzezinski** [comment]
:eyes: didn't realize this was even a thing... oops #34

**Comment by mattBrzezinski** [comment]
@ararslan any capacity to finish this off? I can close my PR if anything. I'll update the permissions on the stack so this should run successfully.

I will note, we should probably bump versions for other deps while we're here.

**Comment by ararslan** [comment]
> any capacity to finish this off?

Unfortunately not, happy to close if you'd prefer, or feel free to push directly to this branch if you're interested in picking it up from here

**Pull request closed without merging**
