### PR TITLE
Increase sleep time during logs tests

### PR DESCRIPTION
**Pull request by TylerLoewen**
These changes should hopefully fix [this](https://github.com/invenia/CloudWatchLogs.jl/issues/38) reoccurring CI test failure issue.

### CODE REVIEW

**Review by fchorney — APPROVED** [review]

**Comment by TylerLoewen** [comment]
bors try

**Comment by TylerLoewen** [comment]
bors try

**Comment by mattBrzezinski** [comment]
There are a few other sleeps, maybe set a variable for the amount and use it within all of those?

**Comment by TylerLoewen** [comment]
> There are a few other sleeps, maybe set a variable for the amount and use it within all of those?

That is an option but I'm not sure how well that would work since there are sleep values that range from 1, 5, or 10 seconds. If I make them all use the same variable they'd all be 10 seconds which is probably sleeping more than we need for most cases.

**Comment by mattBrzezinski** [comment]
> > There are a few other sleeps, maybe set a variable for the amount and use it within all of those?
> 
> That is an option but I'm not sure how well that would work since there are sleep values that range from 1, 5, or 10 seconds. If I make them all use the same variable they'd all be 10 seconds which is probably sleeping more than we need for most cases.

Yeah that's fair. Tbh these online tests, and testing in general needs to be re-worked as it's just awkward to get stuff to work together when you're creating/deleting resources really quickly.

**Comment by TylerLoewen** [comment]
> > > There are a few other sleeps, maybe set a variable for the amount and use it within all of those?
> > 
> > 
> > That is an option but I'm not sure how well that would work since there are sleep values that range from 1, 5, or 10 seconds. If I make them all use the same variable they'd all be 10 seconds which is probably sleeping more than we need for most cases.
> 
> Yeah that's fair. Tbh these online tests, and testing in general needs to be re-worked as it's just awkward to get stuff to work together when you're creating/deleting resources really quickly.

Ya this is definitely not a permanent solution but hopefully this will make the CI less noisy for the time being.

**Review by mattBrzezinski — APPROVED** [review]

**Pull request merged**
