### PR TITLE
Use the built-in Travis codecov step now that it's fixed

### PR DESCRIPTION
**Pull request by ararslan**
It should no longer shadow errors. See https://github.com/travis-ci/travis-build/pull/1568.

### CODE REVIEW

**Comment by iamed2** [comment]
Won't the current state mean that if _coverage_ fails then the tests will fail? Also it showed a test failure marked as an error rather than a failure, which seems like things were made worse...

**Comment by ararslan** [comment]
cc @simonbyrne

**Comment by iamed2** [comment]
It's not actually waiting on Simon, but another person: https://github.com/travis-ci/travis-build/pull/1571

**Comment by ararslan** [comment]
Seems Travis is no longer used here.

**Pull request closed without merging**
